# fly.toml app configuration file for context7
app = 'context7'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 75
    soft_limit = 50

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/ping"

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
