# fly.toml app configuration file for context7
app = 'context7'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  concurrency.type = "connections"
  concurrency.hard_limit = 100
  concurrency.soft_limit = 80

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
